export const cat = [
  'ملابس واقية',
  'امان الرأس',
  'احذية امان',
  'انذارات',
  'حريق',
];
export const products = [
  {
    title: 'افارول',
    category: 'ملابس واقية',
  },
  {
    title: 'بدلة',
    category: 'ملابس واقية',
  },
  {
    title: 'جاكيت',
    category: 'ملابس واقية',
  },
  {
    title: 'بالطو',
    category: 'ملابس واقية',
  },
  {
    title: 'فيست',
    category: 'ملابس واقية',
  },
  {
    title: 'جوانتي',
    category: 'ملابس واقية',
  },
  {
    title: 'حزام',
    category: 'ملابس واقية',
  },
  {
    title: 'خوذة',
    category: 'امان الرأس',
  },
  {
    title: 'نظارة',
    category: 'امان الرأس',
  },
  {
    title: 'ماسك',
    category: 'امان الرأس',
  },
  {
    title: 'كمامة',
    category: 'امان الرأس',
  },
  {
    title: 'اوفرهيد',
    category: 'امان الرأس',
  },
  {
    title: 'دقانة',
    category: 'امان الرأس',
  },
  {
    title: 'سدادة',
    category: 'امان الرأس',
  },
  {
    title: 'فلتر',
    category: 'امان الرأس',
  },
  {
    title: 'سيفتي',
    category: 'احذية امان',
  },
  {
    title: 'بندا',
    category: 'احذية امان',
  },
  {
    title: 'لوحة',
    category: 'انذارات',
  },
  {
    title: 'فليشر',
    category: 'انذارات',
  },
  {
    title: 'عصا مرور',
    category: 'انذارات',
  },
  {
    title: 'شريط حاجز',
    category: 'انذارات',
  },
  {
    title: 'شريط لاصق',
    category: 'انذارات',
  },
  {
    title: 'بكرة احترس',
    category: 'انذارات',
  },
  {
    title: 'بشبوري',
    category: 'حريق',
  },
];
export const items = [
  { title: 'بدلة 2 قطعه اخضر xزيتي', qty: 5, sell_price: 550, cost_price: 500 },
  { title: 'افارول كحلي', qty: 38, sell_price: 550, cost_price: 350 },
  { title: 'افارول برتقالي', qty: 43, sell_price: 450, cost_price: 350 },
  { title: 'افارول زيتي قطن', qty: 16, sell_price: 450, cost_price: 300 },
  {
    title: 'بدلة 2 قطعه كحلي xلبني',
    qty: 11,
    sell_price: 550,
    cost_price: 400,
  },
  { title: 'افارول قطن لبني sso', qty: 8, sell_price: 550, cost_price: 375 },
  { title: 'افارول زيتي بوليستر', qty: 13, sell_price: 450, cost_price: 300 },
  { title: 'جاكيت مطر فسفوري', qty: 12, sell_price: 250, cost_price: 125 },
  { title: 'بالطو مطر تقيل كحلي', qty: 1, sell_price: 350, cost_price: 230 },
  { title: 'فيست عمال برتقالي', qty: 17, sell_price: 55, cost_price: 35 },
  { title: 'بالطو مطر خفيف كحلي', qty: 3, sell_price: 220, cost_price: 120 },
  { title: 'بالطو احماض', qty: 35, sell_price: 230, cost_price: 180 },
  { title: 'بدلة احماض', qty: 2, sell_price: 250, cost_price: 150 },
  {
    title: 'جوانتي ضد القطع احمر',
    qty: 156,
    sell_price: 384 / 12,
    cost_price: 336 / 12,
  },
  {
    title: 'جوانتي ضد القطع اخضر في اسود',
    qty: 192,
    sell_price: 384 / 12,
    cost_price: 336 / 12,
  },
  {
    title: 'جوانتي ضد القطع برتقالي',
    qty: 540,
    sell_price: 420 / 12,
    cost_price: 324 / 12,
  },
  {
    title: 'حزام امان 2 هوك تيواني',
    qty: 3,
    sell_price: 1650,
    cost_price: 1200,
  },
  {
    title: 'فيست مهندسين برتقالي عادي',
    qty: 30,
    sell_price: 120,
    cost_price: 100,
  },
  {
    title: 'فيست مهندسين اسود عادي',
    qty: 24,
    sell_price: 120,
    cost_price: 100,
  },
  {
    title: 'فيست مهندسين ازرق عادي',
    qty: 30,
    sell_price: 120,
    cost_price: 100,
  },
  { title: 'فيست عمال فسفوري', qty: 293, sell_price: 55, cost_price: 35 },
  {
    title: 'جوانتي لحام احمر طويل 40سم',
    qty: 408,
    sell_price: 1800 / 12,
    cost_price: 1440 / 12,
  },
  {
    title: 'حزام امان كلنيكس 2 هوك',
    qty: 2,
    sell_price: 2500,
    cost_price: 2000,
  },
  { title: 'حزام امان 1هوك', qty: 2, sell_price: 950, cost_price: 650 },
  { title: 'جوانتي شرقيه', qty: 55, sell_price: 75, cost_price: 60 },
  { title: 'افارول ssoاحمر', qty: 1, sell_price: 550, cost_price: 350 },
  { title: 'دقانة', qty: 60, sell_price: 20, cost_price: 10 },
  {
    title: 'نظارة 3m ابيض',
    qty: 432,
    sell_price: 600 / 36,
    cost_price: 276 / 36,
  },
  { title: 'بالطو اليوم الواحد', qty: 20, sell_price: 16, cost_price: 12 },
  { title: 'ماسك وجه كامل 3m', qty: 3, sell_price: 3000, cost_price: 1500 },
  { title: 'لوحة مضئة exit', qty: 25, sell_price: 280, cost_price: 200 },
  { title: 'فليشر الوان سارينة', qty: 11, sell_price: 350, cost_price: 200 },
  { title: 'سيفتي واك عماني', qty: 48, sell_price: 550, cost_price: 440 },
  {
    title: 'بشبوري متعدد الومنيوم 2.5 بوصه',
    qty: 5,
    sell_price: 830,
    cost_price: 680,
  },
  {
    title: 'بشبوري عادي نحاس 2.5بوصه',
    qty: 3,
    sell_price: 930,
    cost_price: 780,
  },
  { title: 'خوذة كاب', qty: 3, sell_price: 350, cost_price: 285 },
  { title: 'ماسك فلتر واحد 305', qty: 32, sell_price: 85, cost_price: 60 },
  { title: 'كيس اوفرهيد', qty: 85, sell_price: 40, cost_price: 30 },
  { title: 'كمامة kn95', qty: 930, sell_price: 110 / 10, cost_price: 80 / 10 },
  {
    title: 'جوانتي اسود ميكانيكا',
    qty: 348,
    sell_price: 264 / 12,
    cost_price: 216 / 12,
  },
  { title: 'نظارة سودة مستورة', qty: 17, sell_price: 360, cost_price: 240 },
  { title: 'نظارة جوجل', qty: 70, sell_price: 1000 / 10, cost_price: 600 / 10 },
  {
    title: 'نظارة سوداء 3m',
    qty: 276,
    sell_price: 600 / 12,
    cost_price: 276 / 12,
  },

  { title: 'لوحة مضيئة exit اكلرك', qty: 2, sell_price: 350, cost_price: 280 },
  { title: 'سدادة اذن سيليكون بعلبه', qty: 250, sell_price: 15, cost_price: 8 },
  { title: 'جوانتي ارجون', qty: 68, sell_price: 85, cost_price: 65 },
  {
    title: 'جوانتي محبب احمر قطن',
    qty: 72,
    sell_price: 360 / 12,
    cost_price: 264 / 12,
  },
  {
    title: 'جوانتي محبب تريكو',
    qty: 168,
    sell_price: 360 / 12,
    cost_price: 300 / 12,
  },
  { title: 'ماسك نص وجه 3m 6200', qty: 14, sell_price: 430, cost_price: 350 },
  { title: 'فلتر 3m 6057', qty: 12, sell_price: 460, cost_price: 350 },
  { title: 'ماسك وجه كامل امريكي', qty: 2, sell_price: 2500, cost_price: 1500 },
  { title: 'جوانتي صدمات', qty: 13, sell_price: 350, cost_price: 285 },
  {
    title: 'جوانتي ضد القطع اصفر xاخضر',
    qty: 31,
    sell_price: 28,
    cost_price: 18,
  },
  {
    title: 'جوانتي working ضد القطع',
    qty: 120,
    sell_price: 1200 / 12,
    cost_price: 720 / 12,
  },
  {
    title: 'جوانتي الكهرباء احمر x اسود',
    qty: 10,
    sell_price: 60,
    cost_price: 25,
  },
  { title: 'خوذة msa اخضر', qty: 79, sell_price: 220, cost_price: 125 },
  { title: 'خوذة msa ابيض', qty: 19, sell_price: 220, cost_price: 125 },
  { title: 'خوذة msa صفراء', qty: 77, sell_price: 220, cost_price: 125 },
  { title: 'خوذة عمال زرقاء', qty: 25, sell_price: 45, cost_price: 25 },
  { title: 'خوذة msa حمراء', qty: 8, sell_price: 220, cost_price: 125 },
  { title: 'خوذة msa رمادي', qty: 3, sell_price: 220, cost_price: 125 },
  { title: 'خوذة بيضاء اسباني', qty: 41, sell_price: 100, cost_price: 70 },
  { title: 'خوذة عمال بيضاء', qty: 42, sell_price: 45, cost_price: 25 },
  { title: 'خوذة عمال ازرق', qty: 26, sell_price: 45, cost_price: 25 },
  { title: 'خوذة عمال اصفر', qty: 110, sell_price: 45, cost_price: 25 },
  { title: 'خوذة عمال حمراء', qty: 46, sell_price: 45, cost_price: 25 },
  { title: 'افارول مستورد', qty: 23, sell_price: 550, cost_price: 250 },
  { title: 'فيست كحلي عمال', qty: 22, sell_price: 55, cost_price: 35 },
  { title: 'فيست عمال اسود', qty: 18, sell_price: 55, cost_price: 35 },
  { title: 'فيست عمال احمر', qty: 21, sell_price: 55, cost_price: 35 },
  { title: 'فيست عمال 3m', qty: 1, sell_price: 150, cost_price: 100 },
  { title: 'سيفتي bear خفيف', qty: 6, sell_price: 750, cost_price: 525 },
  { title: 'سيفتي bear تقيل', qty: 2, sell_price: 650, cost_price: 425 },
  { title: 'سيفتي بلاس مكتبي', qty: 6, sell_price: 620, cost_price: 520 },
  { title: 'سيفتي ارماني', qty: 6, sell_price: 470, cost_price: 380 },
  { title: 'سيفتي sso', qty: 1, sell_price: 650, cost_price: 475 },
  { title: 'سيفتي المنار', qty: 1, sell_price: 750, cost_price: 550 },
  { title: 'سيفتي جاسكو', qty: 1, sell_price: 1500, cost_price: 1200 },
  { title: 'سيفتي فخامه ومو', qty: 17, sell_price: 450, cost_price: 350 },
  { title: 'سيفتي تايجر', qty: 4, sell_price: 500, cost_price: 450 },
  { title: 'سيفتي باتا', qty: 2, sell_price: 1000, cost_price: 700 },
  { title: 'بندا تريكا 1509', qty: 4, sell_price: 1050, cost_price: 750 },
  { title: 'بندا تريكا 1007', qty: 1, sell_price: 750, cost_price: 500 },
  { title: 'سيفتي ارو', qty: 2, sell_price: 350, cost_price: 250 },
  {
    title: 'سيفتي باندا ايطالي s3',
    qty: 4,
    sell_price: 1450,
    cost_price: 1000,
  },
  { title: 'سيفتي هيما', qty: 2, sell_price: 650, cost_price: 450 },
  { title: 'سيفتي كروكو', qty: 1, sell_price: 450, cost_price: 280 },
  { title: 'بالطو كحلي ولبني', qty: 5, sell_price: 150, cost_price: 100 },
  { title: 'اوفرهيد كيس', qty: 85, sell_price: 40, cost_price: 30 },
  { title: 'سيفتي بلاس هاف', qty: 1, sell_price: 550, cost_price: 500 },
  { title: 'سيفتي ريدوينج', qty: 2, sell_price: 4500, cost_price: 3500 },
  { title: 'سيفتي بيزول', qty: 2, sell_price: 2500, cost_price: 1500 },
];
/*
{ title: 'طقم امني قميص وبنطلون', qty: 1, sell_price: 500, cost_price: 400 },
 
  { title: 'بكرة احترس منطقه عمل', qty: 24, sell_price: 100, cost_price: 65 },

  { title: 'بكرة صرف صحي', qty: 20, sell_price: 110, cost_price: 65 },

  { title: 'بكرة سلك جنزير صغير', qty: 2, sell_price: 500, cost_price: 350 },
  { title: 'عصا مرور', qty: 3, sell_price: 180, cost_price: 130 },
  {
    title: 'شريط تحزير احمر في ابيض بلاستك',
    qty: 1,
    sell_price: 550,
    cost_price: 400,
  },
  {
    title: 'شريط تحزير احمر في ابيض ورق',
    qty: 11,
    sell_price: 110,
    cost_price: 75,
  },
  {
    title: 'شريط تحزير احمر في اصفر مضئ',
    qty: 1,
    sell_price: 325,
    cost_price: 220,
  },
    { title: 'شريط حاجز', qty: 6, sell_price: 100, cost_price: 65 },
  {
    title: 'شريط لاصق مخرفش 2لون (احمرxابيض)',
    qty: 23,
    sell_price: 120,
    cost_price: 100,
  },
  */
//! { title: 'اوفرهيد كيس', qty: 85, sell_price: 40, cost_price: 30 }
