export enum RoleEnum {
  OWNER = 'owner',
  READER = 'reader',
  ADMIN = 'admin',
}

export enum GovernoratesEnums {
  Cairo = 'Cairo',
  Giza = 'Giza',
  Alexandria = 'Alexandria',
  Qalyubia = 'Qalyubia',
  Dakahlia = 'Dakahlia',
  Sharqia = 'Sharqia',
  Beheira = 'Beheira',
  KafrElSheikh = 'Kafr El-Sheikh',
  Gharbia = 'Gharbia',
  Monufia = 'Monufia',
  Damietta = 'Damietta',
  PortSaid = 'Port Said',
  Ismailia = 'Ismailia',
  Suez = 'Suez',
  NorthSinai = 'North Sinai',
  SouthSinai = 'South Sinai',
  RedSea = 'Red Sea',
  Fayoum = 'Fayoum',
  BeniSuef = 'Beni Suef',
  Minya = 'Minya',
  Assiut = 'Assiut',
  Sohag = 'Sohag',
  Qena = 'Qena',
  Luxor = 'Luxor',
  Aswan = 'Aswan',
  NewValley = 'New Valley',
  Matrouh = 'Matrouh',
}
